# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGH631wLVpTBY2eMkysLZe-NIyyxR3-Y
"""

from pydantic.types import Json
import uvicorn 
from fastapi import FastAPI
from fastapi.encoders import jsonable_encoder
from typing import List
import numpy as np 
import joblib 
from pydantic import BaseModel

class Sale(BaseModel):
    house : str    
    location : str
    bed : int
    bathroom : int
    toilet : int

# 2. Create app and model objects
app = FastAPI()

model = joblib.load("Model.sav")

@app.get("/")
def index():
    return {"API": "Let's do this"}

@app.post("/predict", response_model=Sale, status_code=200)
def get_prediction(data: Sale):
    data = data.dict()
    house = data['house-type']
    location = data['locations']
    bed = data['bed']
    bathroom = data['bathroom']
    toilet = data['toilet']
    result = model.predict([house, location, bed, bathroom, toilet])
    
    if result:
      return jsonify(data, result)

    else:
      return {"status": 404,
              "body": {"Message": "Are you sure you're using the right data ?"}}

# 4. Run the API with uvicorn
#    Will run on http://127.0.0.1:8000
if __name__ == '__main__':
    uvicorn.run(app, host='127.0.0.1', port=8000)